name: Deployment
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Choose env
        options:
        - dev
        - qa
        - prod
jobs:
  get-tasks:
    name: set tasks (${{ github.event.inputs.env }})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env }}
    outputs:
      EXEC_TASKS: ${{ steps.set-tasks.outputs.tasks }}
    steps:
      - uses: actions/github-script@v7
        id: set-tasks
        env:
          U_TASKS: 'deploy,test,load-test'
        with:
          result-encoding: string
          retries: 3
          script: |
            const env = context.payload.inputs.env;
            console.log(`env: ${env}`);
            const tasks = process.env.U_TASKS;
            core.setOutput('tasks', JSON.stringify(tasks.split(',')))
  tasks:
    name: ${{ matrix.task }}
    needs: [get-tasks]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ${{ fromJson(needs.get-tasks.outputs.tasks) }}  
    steps:
      - name: Use matrix
        run: echo "Execute ${{ matrix.task }}"
