name: Package
on:
  push:
  pull_request:
jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ['folder1', 'folder2']
    steps:
      - uses: actions/checkout@v3
      
      - name: Pack Upload ${{ matrix.folder }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.folder }}.zip
          path: |
            ${{ matrix.folder }}
          retention-days: 90
            
      # - name: Pack Upload folder2
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: folder2.zip
      #     path: |
      #       folder2
      #     retention-days: 90
