name: Package
on:
  push:
  pull_request:
jobs:
  find-folders:
    name: Find Folders
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.jobs.outputs.folders }}
    steps:
      - uses: actions/checkout@v3
      - id: jobs
        uses: philips-labs/list-folder-action@v2
        with:
          path: '.'
          
  package:
    name: Package folders
    needs: [find-folders]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-folders.outputs.folders )}}
    steps:
      - uses: actions/checkout@v3
          
      - name: Pack Upload ${{ matrix.folder }}
        if: ${{ !contains(fromJson('[".github", ".git"]'), matrix.folder) }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.folder }}.zip
          path: |
            ${{ matrix.folder }}
          retention-days: 90
