name: Package
on:
  push:
  pull_request:
jobs:
  find-folders:
    name: Find Folders
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ toJSON(steps.*.outputs.value) }}
    steps:
      - uses: actions/checkout@v3
      - name: Collect folders
        id: matrix
        run: |
          ignore_folders=(".github" ".git")
          let i=1
          declare -a dirs
          for d in */
          do
              dir="${d%/}"
              echo "$((i++)) $dir"
              if [[ ${ignore_folders[@]} =~ $dir ]]
              then
                echo "ignoring $dir"
              else
                echo "collecting $dir"
                echo "value=$dir" >> $GITHUB_OUTPUT
              fi
          done

      - name: Show folders
        run: |
           echo "${{ toJSON(steps.*.outputs.value) }}"
        
  package:
    name: Package folders
    needs: [find-folders]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJSON(needs.find-folders.outputs.folders) }}
        
    steps:
      - uses: actions/checkout@v3
          
      - name: Pack Upload ${{ matrix.folder }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.folder }}.zip
          path: |
            ${{ matrix.folder }}
          retention-days: 90
