name: Package
on:
  push:
  pull_request:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create zip files
        run: 
          zip -r -q folder1.zip folder1
          zip -r -q folder2.zip folder2
        
      - uses: actions/upload-artifact@v2
        with:
          name: package.zip
          path: |
            folder1.zip
            folder2.zip
  
