name: Package
on:
  push:
  pull_request:
jobs:
  find-folders:
    name: Find Folders
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.matrix.outputs.value }}
    steps:
      - uses: actions/checkout@v3
      - id: matrix
        run: |
          ignore_folders=(".github" ".git")
          let i=1
          for dir in "${dirs[@]}"; do
              echo "$((i++)) $dir"
              if [[ ${ignore_folders[@]} =~ $dir ]]
              then
                echo "ignoring $dir"
              else
                echo "collecting $dir"
                echo "value=$dir" >> $GITHUB_OUTPUT
              fi
          done
     
  package:
    name: Package folders
    needs: [find-folders]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: ${{ fromJson(needs.find-folders.outputs.folders )}}
    steps:
      - uses: actions/checkout@v3
          
      - name: Pack Upload ${{ matrix.folder }}
        if: ${{ !contains(fromJson('[".github", ".git"]'), matrix.folder) }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.folder }}.zip
          path: |
            ${{ matrix.folder }}
          retention-days: 90
